server:
  port: 8071
spring:
  application:
    name: shop-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect