server:
  port: 7000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          order: 1
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1